const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

    //user
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
    PROCESS_LOGOUT: "PROCESS_LOGOUT",

    //admin
    FETCH_ROLE_START: "FETCH_ROLE_START",
    FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

    FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",

    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_FAILED: "EDIT_USER_FAILED",

    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILED: "DELETE_USER_FAILED",

    FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
    FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",
    FETCH_ALL_PASSENGERS_SUCCESS: "FETCH_ALL_PASSENGERS_SUCCESS",
    FETCH_ALL_PASSENGERS_FAILED: "FETCH_ALL_PASSENGERS_FAILED",

    //location
    FETCH_LOCATION_SUCCESS: "FETCH_LOCATION_SUCCESS",
    FETCH_LOCATION_FAILED: "FETCH_LOCATION_FAILED",

    FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
    FETCH_CITY_FAILED: "FETCH_CITY_FAILED",

    CREATE_LOCATION_SUCCESS: "CREATE_LOCATION_SUCCESS",
    CREATE_LOCATION_FAILED: "CREATE_LOCATION_FAILED",

    EDIT_LOCATION_SUCCESS: "EDIT_LOCATION_SUCCESS",
    EDIT_LOCATION_FAILED: "EDIT_LOCATION_FAILED",

    DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS",
    DELETE_LOCATION_FAILED: "DELETE_LOCATION_FAILED",

    //BusType
    FETCH_BUS_TYPES_SUCCESS: "FETCH_BUS_TYPES_SUCCESS",
    FETCH_BUS_TYPES_FAILED: "FETCH_BUS_TYPES_FAILED",

    //Route
    FETCH_ROUTES_SUCCESS: "FETCH_ROUTES_SUCCESS",
    FETCH_ROUTES_FAILED: "FETCH_ROUTES_FAILED",

    FETCH_ROUTES_HOME_SUCCESS: "FETCH_ROUTES_HOME_SUCCESS",
    FETCH_ROUTES_HOME_FAILED: "FETCH_ROUTES_HOME_FAILED",

    FETCH_BLOGS_SUCCESS: "FETCH_BLOGS_SUCCESS",
    FETCH_BLOGS_FAILED: "FETCH_BLOGS_FAILED",

    //Vehicle
    FETCH_VEHICLES_SUCCESS: "FETCH_VEHICLES_SUCCESS",
    FETCH_VEHICLES_FAILED: "FETCH_VEHICLES_FAILED",

    DELETE_VEHICLE_SUCCESS: "DELETE_VEHICLE_SUCCESS",
    DELETE_VEHICLE_FAILED: "DELETE_VEHICLE_FAILED",

    //shcedule
    FETCH_SCHEDULES_SUCCESS: "FETCH_SCHEDULES_SUCCESS",
    FETCH_SCHEDULES_FAILED: "FETCH_SCHEDULES_FAILED",

    DELETE_SCHEDULES_SUCCESS: "DELETE_SCHEDULES_SUCCESS",
    DELETE_SCHEDULES_FAILED: "DELETE_SCHEDULES_FAILED",

    //arr seat
    FETCH_ARR_SEAT_SUCCESS: "FETCH_ARR_SEAT_SUCCESS",
    FETCH_ARR_SEAT_FAILED: "FETCH_ARR_SEAT_FAILED",

    //tickets
    FETCH_TICKET_SUCCESS: "FETCH_TICKET_SUCCESS",
    FETCH_TICKET_FAILED: "FETCH_TICKET_FAILED",

    //events
    FETCH_EVENT_SUCCESS: "FETCH_EVENT_SUCCESS",
    FETCH_EVENT_FAILED: "FETCH_EVENT_FAILED",

    FETCH_EVENT_HOME_SUCCESS: "FETCH_EVENT_HOME_SUCCESS",
    FETCH_EVENT_HOME_FAILED: "FETCH_EVENT_HOME_FAILED",
    //coupons
    FETCH_COUPON_SUCCESS: "FETCH_COUPON_SUCCESS",
    FETCH_COUPON_FAILED: "FETCH_COUPON_FAILED",
});

export default actionTypes;
